name:         Downtown Sound 2015
pygments:     true
baseurl:      "http://downtownsound.org"
url:          http://localhost:4000
permalink:    /:month-:day-:year/
timezone:     -0500
future:       true
markdown:     kramdown