name:         Millennium Park Summer Concerts
pygments:     true
baseurl:      "http://concerts.brynosaur.com"
url:          http://localhost:4000
permalink:    /:categories/:title/
future:       true