name:         Downtown Sound 2015
pygments:     true
baseurl:      "http://downtownsound.net"
url:          http://localhost:4000
permalink:    /:categories/:title/
future:       true
markdown:     kramdown